version: '3.8'

services:
  mysql:
    image: mysql:8.0.35-debian
    container_name: mysql_dev
    restart: always
    env_file: docker/development/.env
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  apache:
    build: ./docker/development
    container_name: apache_dev
    restart: always
    volumes:
      - ./api:/var/www/html/api
      - ./db:/var/www/html/db
      - ./utils:/var/www/html/utils
      - ./dbconfiguration.yml:/var/www/html/dbconfiguration.yml  # ⬅️ Línea añadida
      - ./docker/development/apache-dev.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
