version: '3.8'

services:
  mysql:
    image: mysql:8.0.35-debian
    container_name: mysql_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: films
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  apache:
    build: ./docker/development  # Ruta correcta al Dockerfile
    container_name: apache_dev
    restart: always
    volumes:
      - ./app:/var/www/html  # Comparte la carpeta con el código fuente
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
